name: Process data from Lark backup
on:
  repository_dispatch:
    types:
      - l0y1-lark-backup-changed
  workflow_dispatch:

jobs:
  process-lark-backup:
    runs-on: ubuntu-latest
    env:
      APP_ID: ${{ secrets.LARK_APP_ID }}
      APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
      IGNORED_TABLE: ${{ vars.LARK_IGNORED_TABLE }}
    steps:
      - name: Create temp dirs
        run: mkdir data-lark-backup data-src site-src site-dist
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.event.client_payload.source }}
          ref: ${{ github.event.client_payload.ref }}
          path: data-lark-backup
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ secrets.KB_REPO }}
          ref: master
          path: data-src
      - uses: actions/checkout@v3
        with:
          ref: main
          path: site-src
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: false
          path: site-dist
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.15.3
      - run: |
          cd site-src
          cp .env.example .env.local
          sed -i -e "s/^KNOSYS_LARK_BACKUP_DATA_SOURCE=.*/KNOSYS_LARK_BACKUP_DATA_SOURCE=..\/data-lark-backup/" -e "s/^KNOSYS_LARK_INDIVIDUAL_APP_ID=.*/KNOSYS_LARK_INDIVIDUAL_APP_ID=$APP_ID/" -e "s/^KNOSYS_LARK_INDIVIDUAL_APP_SECRET=.*/KNOSYS_LARK_INDIVIDUAL_APP_SECRET=$APP_SECRET/" .env.local
          npm i
          npm run sync lark task true $APP_ID $APP_SECRET $IGNORED_TABLE
          npm run ics .knosys/caches/sync/open-tasks.yml
          rm -rf ../site-dist/schedule.ics
          cp schedule.ics ../site-dist/
          cd ..
      - name: Commit changes
        run: |
          cd site-dist
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update \`schedule.ics\`"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          directory: site-dist
